PomMVC/Controllers/VersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PomMVC.Models;

namespace PomMVC.Controllers
{
    [Authorize]
    public class VersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Vers
        public ActionResult Index()
        {
            return View(db.Versions.ToList());
        }

        // GET: Vers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ver vers = db.Versions.Find(id);
            if (vers == null)
            {
                return HttpNotFound();
            }
            return View(vers);
        }

        // GET: Vers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VerID,VerNo")] Ver vers)
        {
            if (ModelState.IsValid)
            {
                db.Versions.Add(vers);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vers);
        }

        // GET: Vers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ver vers = db.Versions.Find(id);
            if (vers == null)
            {
                return HttpNotFound();
            }
            return View(vers);
        }

        // POST: Vers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VerID,VerNo")] Ver vers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vers);
        }

        // GET: Vers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ver vers = db.Versions.Find(id);
            if (vers == null)
            {
                return HttpNotFound();
            }
            return View(vers);
        }

        // POST: Vers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ver vers = db.Versions.Find(id);
            db.Versions.Remove(vers);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PomMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - POM</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("POM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>                   
                    <li>@Html.ActionLink("Projects", "Index", "Projects")</li>
                    <li>@Html.ActionLink("Versions", "Index", "Vers")</li>
                    <li>@Html.ActionLink("Pages", "Index", "Pages")</li>
                    <li>@Html.ActionLink("Transactions", "Index", "Transactions")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - POM</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>